version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    container_name: todo-app
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - ./docker/app/php.ini:/usr/local/etc/php/conf.d/custom.ini
    depends_on:
      - database
    networks:
      - todo-network

  web:
    image: nginx:alpine
    container_name: todo-nginx
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - todo-network
  database:
    image: mysql:8.0
    container_name: todo-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    ports:
      - "24305:3306"
    volumes:
      - todo-mysql-data:/var/lib/mysql
    networks:
      - todo-network
  node:
    image: node:18-alpine
    container_name: todo-node
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    ports:
      - "8084:8084"
    command: sh -c "npm install && npm run dev"
    networks:
      - todo-network

networks:
  todo-network:
    driver: bridge

volumes:
  todo-mysql-data:
    driver: local